language: node_js
node_js:
  - "stable"
  - "iojs"
notifications:
  irc:
    channels:
      - "chat.freenode.net#bionode"
    template:
      - "%{message}: %{repository}#%{build_number}: %{commit_message} (%{branch} - %{commit} : %{author})"
